/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Observer } from "./Observer";
import { ObserverCountArgs } from "./ObserverCountArgs";
import { ObserverFindManyArgs } from "./ObserverFindManyArgs";
import { ObserverFindUniqueArgs } from "./ObserverFindUniqueArgs";
import { DeleteObserverArgs } from "./DeleteObserverArgs";
import { ObserverService } from "../observer.service";
@graphql.Resolver(() => Observer)
export class ObserverResolverBase {
  constructor(protected readonly service: ObserverService) {}

  async _observersMeta(
    @graphql.Args() args: ObserverCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Observer])
  async observers(
    @graphql.Args() args: ObserverFindManyArgs
  ): Promise<Observer[]> {
    return this.service.observers(args);
  }

  @graphql.Query(() => Observer, { nullable: true })
  async observer(
    @graphql.Args() args: ObserverFindUniqueArgs
  ): Promise<Observer | null> {
    const result = await this.service.observer(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Observer)
  async deleteObserver(
    @graphql.Args() args: DeleteObserverArgs
  ): Promise<Observer | null> {
    try {
      return await this.service.deleteObserver(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
